//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string YearLevel { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Purok { get; set; }
        public string Street { get; set; }
    }
}
